sonic:
  policy: 'CnnPolicy'
  n_steps: 256 # este valor parece não mudar assim que começa o learning, deve ficar associado ao modelo
  n_epochs: 4
  batch_size: 256
  learning_rate: lin_2.5e-4
  clip_range: lin_0.1
  vf_coef: 0.5
  ent_coef: 0.01